# Generated by Django 5.0.2 on 2024-02-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notechange',
            name='changes',
        ),
        migrations.AddField(
            model_name='notechange',
            name='changes_to_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notechange',
            name='changes_to_title',
            field=models.TextField(default=''),
        ),
    ]
